apiVersion: apps/v1
kind: Deployment
metadata:
  name: student-management
spec:
  replicas: 2  # Number of pod replicas
  selector:
    matchLabels:
      app: student-management
  template:
    metadata:
      labels:
        app: student-management
    spec:
      containers:
        - name: student-management
          image: astitva8796/student-management:latest
          ports:
            - containerPort: 8080
          env:
            - name: SPRING_PROFILES_ACTIVE
              value: "prod"  # Change based on your profile
